from typing import Annotated, Any, List, Literal, Optional, Union
from pydantic import BaseModel, BeforeValidator, Field
from fastapi import APIRouter, HTTPException, Depends, status
import torch
from sentence_transformers import SentenceTransformer

# --- Pydantic Schemas (from OpenAPI Specification) ---

# Nested Schemas
class Usage(BaseModel):
    """Usage statistics for the completion request."""
    prompt_tokens: int = Field(..., description="The number of tokens used by the prompt.")
    total_tokens: int = Field(..., description="The total number of tokens used by the request.")

class Embedding(BaseModel):
    """Represents an embedding vector."""
    index: int = Field(..., description="The index of the embedding in the list of embeddings.")
    embedding: List[float] = Field(..., description="The embedding vector, a list of floats.")
    # FIX: Replaced Field(..., const=True) with Literal["embedding"] for Pydantic V2
    object: Literal["embedding"] = "embedding" 

# Helper function to ensure single string input is converted to a list
def ensure_list_for_input(v: Any) -> Any:
    """Ensure the input field is a list if it's a single string."""
    if isinstance(v, str):
        return [v]
    return v

# Define the constrained list type using Annotated
# This type now requires the list to contain strings and have a minimum length of 1.
ConstrainedStringList = Annotated[
    List[str], 
    Field(min_length=1)
]

# Request Schema (No change needed here, as it didn't use const=True)
class CreateEmbeddingRequest(BaseModel):
    """Request payload for creating embeddings."""
    input: Annotated[
        Union[str, ConstrainedStringList],
        BeforeValidator(ensure_list_for_input)
    ] = Field(..., description="Input text to embed, encoded as a string or array of strings.")
    model: str = Field(..., description="ID of the model to use.")
    encoding_format: Optional[str] = Field("float", pattern="^(float|base64)$", description="The format to return the embeddings in.")
    user: Optional[str] = Field(None, description="A unique identifier representing your end-user.")

# Response Schema
class CreateEmbeddingResponse(BaseModel):
    """Response payload containing generated embeddings."""
    data: List[Embedding] = Field(..., description="The list of embeddings generated by the model.")
    model: str = Field(..., description="The name of the model used to generate the embedding.")
    # FIX: Replaced Field(..., const=True) with Literal["list"] for Pydantic V2
    object: Literal["list"] = "list"
    usage: Usage 

# Error Response Schema
class ErrorDetail(BaseModel):
    message: str
    type: str
    param: Optional[str] = None
    code: Optional[str] = None

class ErrorResponse(BaseModel):
    error: ErrorDetail

# Configuration
MODEL_PATH = "static/models/embeddinggemma-300m"
TARGET_MODEL_NAME = "embeddinggemma-300m"
EMBEDDING_ROUTER = APIRouter(prefix="/v1", tags=["llm"])
CURRENT_DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Global variable to hold the loaded model
S_MODEL = None

def load_model():
    """Load the SentenceTransformer model from the specified path."""
    global S_MODEL
    try:
        print(f"Loading SentenceTransformer model from: {MODEL_PATH}...")
        
        # NOTE: Using SentenceTransformer to load the downloaded model
        S_MODEL = SentenceTransformer(MODEL_PATH, device=CURRENT_DEVICE)
        print("Model loaded successfully!")
    except ImportError:
        # Handle the case where the library is not installed
        raise RuntimeError("SentenceTransformer library not found. Please run 'pip install sentence-transformers'.")
    except Exception as e:
        # Handle file not found or model loading errors
        print(f"Error loading model from {MODEL_PATH}: {e}")
        raise RuntimeError(f"Failed to load model from path: {MODEL_PATH}")

# Call model loading function at startup (can be done in main app startup event)
# load_model()

# Dependency to ensure the model is loaded before processing requests
def get_model():
    if S_MODEL is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "error": {
                    "message": "Model not yet loaded or failed to load.",
                    "type": "server_error",
                    "code": "model_unavailable"
                }
            }
        )
    return S_MODEL

@EMBEDDING_ROUTER.post(
    "/embeddings",
    response_model=CreateEmbeddingResponse,
    status_code=status.HTTP_200_OK,
    # Define potential error responses
    responses={
        status.HTTP_400_BAD_REQUEST: {"model": ErrorResponse, "description": "Invalid Request"},
        status.HTTP_500_INTERNAL_SERVER_ERROR: {"model": ErrorResponse, "description": "Internal Server Error"},
    }
)
async def create_embedding(
    request: CreateEmbeddingRequest,
    model_inference = Depends(get_model)
):
    """
    Creates an embedding vector representing the input text.
    """
    try:
        # 1. Input Validation and Normalization
        input_data = request.input
        if isinstance(input_data, str):
            input_texts = [input_data]
        elif isinstance(input_data, list):
            input_texts = input_data
        else:
            # Should be caught by Pydantic, but added for robustness
            raise ValueError("Input must be a string or a list of strings.")

        # 2. Model Validation
        if request.model != TARGET_MODEL_NAME:
            # Adhere to the model specified in the request
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail={
                    "error": {
                        "message": f"The model '{request.model}' does not exist or you do not have access to it.",
                        "type": "invalid_request_error",
                        "code": "model_not_found"
                    }
                }
            )

        # 3. Perform Inference
        # Tokenizer for SentenceTransformer is part of the model_inference object
        
        # Encode the texts
        embeddings = model_inference.encode(input_texts, convert_to_numpy=True)
        
        # Calculate token usage (approximated, as SentenceTransformer token counts aren't always available)
        # For a production-ready model, you would use the model's tokenizer for an accurate count.
        # Here we use a basic character-based approximation for demonstration or the S-T tokenizer
        tokens = [len(model_inference.tokenizer.tokenize(t)) for t in input_texts]
        prompt_tokens = sum(tokens)
        total_tokens = prompt_tokens

        # 4. Construct Response
        embedding_data: List[Embedding] = []
        for i, emb in enumerate(embeddings):
            # Convert numpy array to standard Python list of floats
            embedding_data.append(
                Embedding(
                    index=i,
                    embedding=emb.tolist(),
                    object="embedding"
                )
            )

        response = CreateEmbeddingResponse(
            data=embedding_data,
            model=TARGET_MODEL_NAME,
            object="list",
            usage=Usage(
                prompt_tokens=prompt_tokens,
                total_tokens=total_tokens
            )
        )
        return response

    except HTTPException:
        # Re-raise explicit HTTPExceptions (like the 400 for wrong model)
        raise

    except Exception as e:
        # Gracefully handle other unexpected server errors (500)
        print(f"An unexpected error occurred: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "error": {
                    "message": f"Internal server error: {e}",
                    "type": "server_error",
                    "code": "500_internal_error"
                }
            }
        )
